name: My Composite Action
description: A reusable composite action that prints a message.

runs:
  using: "composite"
  steps:
    - name: Print a message
      shell: bash
      run: |
        echo "the message is my msg"