name: my reusuable workflow

on:
  workflow_dispatch:

   
jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: using composite action
        uses: ./.github/actions/composite-action/
    