name: my reusuable workflow

on:
  workflow_dispatch:

   
jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name:  checkout code
        uses: actions/checkout@v6
      - name: using composite action
        uses: ./.github/actions/composite-action/mywork.yaml
    